name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: ci  

    steps:
      - name: (Github) Checkout Code
        uses: actions/checkout@v4

      - name: (SSH) Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: (Docker) SSH into VPS and Deploy Production Environment
        run: |
          ssh -o StrictHostKeyChecking=no root@45.140.142.168 '
            export DOCKER_BUILDKIT=1
            export DOCKER_CLI_EXPERIMENTAL=enabled
            
            docker pull marijndemul16/ddt.frontend:latest
            docker pull marijndemul16/ddt.backend:latest

            cd /root/docker/deepdrunktalks

            docker-compose down

            docker-compose up -d
          '
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_EXPERIMENTAL: enabled
