name: CI

on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: (Github) Checkout Code
        uses: actions/checkout@v4

      - name: (Node.js) Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: (Frontend) Install Dependencies
        working-directory: DeepDrunkTalk.Frontend/
        run: npm install

      - name: (Frontend) Get Changed Files
        id: changed-files
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.js\|\.jsx\|\.ts\|\.tsx')"

      - name: (Frontend) Lint Changed Files
        working-directory: DeepDrunkTalk.Frontend/
        run: |
          files="${{ steps.changed-files.outputs.files }}"
          if [ -n "$files" ]; then
            npx eslint $files --max-warnings 0
          else
            echo "No files to lint"
          fi

      - name: (BuildX) Setup Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: (Docker) Build DeepDrunkTalks Frontend Docker Image
        working-directory: DeepDrunkTalk.Frontend/
        run: docker build . -t marijndemul16/ddt.frontend:latest

      - name: (Docker) Log Into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: (Docker) Push The DeepDrunkTalks Frontend Image To Docker Hub
        run: docker push marijndemul16/ddt.frontend

  backend:
    runs-on: ubuntu-latest
    steps:
      - name: (Github) Checkout Code
        uses: actions/checkout@v4

      - name: (.NET) Setup
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: '8.0.x'

      - name: (.NET) Restore Backend Dependencies
        run: dotnet restore DeepDrunkTalk.Backend/DeepDrunkTalks.Backend.sln

      - name: (Backend) Get Changed Files
        id: changed-files-backend
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.cs')"

      - name: (Backend) Lint Changed Files
        run: |
          files="${{ steps.changed-files-backend.outputs.files }}"
          if [ -n "$files" ]; then
            dotnet format $files --check --verify-no-diagrams
          else
            echo "No files to lint"
          fi

      - name: (.NET) Run Unit Tests
        run: dotnet test --no-build --verbosity normal DeepDrunkTalk.Backend/DeepDrunkTalks.Backend.sln

      - name: (.NET) Build DeepDrunkTalks Backend
        run: dotnet build --no-restore DeepDrunkTalk.Backend/DeepDrunkTalks.Backend.sln

      - name: (BuildX) Setup Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: (Docker) Build DeepDrunkTalks Backend Docker Image
        working-directory: DeepDrunkTalk.Backend/
        run: docker build . -t marijndemul16/ddt.backend:latest

      - name: (Docker) Log Into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: (Docker) Push The DeepDrunkTalks Backend Image To Docker Hub
        run: docker push marijndemul16/ddt.backend
