name: CI/CD

on: 
  push:
    branches: [ main ]

jobs: 
  CICD: 
    runs-on: ubuntu-latest 

    steps:

    - name: (Github) Checkout Code
      uses: actions/checkout@v4

    - name: (.NET) Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: (.NET) Restore DeepDrunkTalks Backend Dependencies
      run: dotnet restore DeepDrunkTalk.Backend/DeepDrunkTalk.Backend.sln

    - name: (.NET) Build DeepDrunkTalks Backend
      run: dotnet build DeepDrunkTalk.Backend/DeepDrunkTalk.Backend.sln --no-restore 

    - name: (.NET) Test DeepDrunkTalks Backend
      run: dotnet test --no-build --verbosity normal DeepDrunkTalk.Backend/DeepDrunkTalk.Backend.sln


