name: CI/CD

on: 
  push:
    branches: [ main ]

jobs: 
  build: 
    runs-on: ubuntu-latest 

    steps: 
    - uses: actions/checkout@v2

    - name: Set up .NET 
      uses: actions/setup-dotnet@v1 
      with: 
        dotnet-version: 8.0 
        
         


