name: CI/CD

on: 
  push:
    branches: [ main ]

jobs: 
  CICD-Frontend: 
    runs-on: ubuntu-latest 

    steps:

    - name: (Github) Checkout Code
      uses: actions/checkout@v4

    - name: (BuildX) Setup Docker BuildX
      uses: docker/setup-buildx-action@v2

    - name: (Docker) Build DeepDrunkTalks Frontend Docker Image 
      working-directory: DeepDrunkTalk.Frontend/
      run: docker build . -t marijndemul16/ddt.frontend:latest

    - name: (Docker) Log Into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: (Docker) Push The DeepDrunkTalks Frontend Image To Docker Hub
      run: docker push marijndemul16/ddt.frontend

  CICD-Backend: 
    runs-on: ubuntu-latest 

    env: 
      DOTNET_INSTALL_DIR: "./.dotnet"

    steps:

    - name: (Github) Checkout Code
      uses: actions/checkout@v4

    - name: (.NET) Setup
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: '8.0.x'

    - name: (.NET) Restore DeepDrunkTalks Backend Dependencies
      run: dotnet restore DeepDrunkTalk.Backend/DeepDrunkTalks.Backend.sln

    - name: (.NET) Build DeepDrunkTalks Backend
      run: dotnet build --no-restore DeepDrunkTalk.Backend/DeepDrunkTalks.Backend.sln 

    - name: (.NET) Test DeepDrunkTalks Backend
      run: dotnet test --no-build --verbosity normal DeepDrunkTalk.Backend/DeepDrunkTalks.Backend.sln

    - name: (Docker) Build DeepDrunkTalks Backend Docker Image 
      working-directory: DeepDrunkTalk.Backend/
      run: docker build . -t marijndemul16/ddt.backend:latest

    - name: (Docker) Log Into Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: (Docker) Push The DeepDrunkTalks Backend Image To Docker Hub
      run: docker push marijndemul16/ddt.backend
  