name: CI/CD

on: 
  push:
    branches: [ main ]

jobs: 
  CICD: 
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v4

    - name: (.NET) Setup
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: (.NET) Restore Dependencies
      run: dotnet restore 

    - name: (.NET) Build DeepDrunkTalks Backend
      run: dotnet build DeepDrunkTalk.Backend/DeepDrunkTalk.Backend.sln --no-restore 




