name: Super-Linter

on: push 

jobs: 
  Super-Linter: 
    name: Lint DeepDrunkTalks Code Base 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v2 
        with: 
          fetch-depth: 0 

      - name: Run Super-Linter 
        uses: github/super-linter@v4 
        
        env: 
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: .*Documentatie/.*
